@startuml ModeloMafiaNucleo
skinparam classAttributeIconSize 0
skinparam linetype ortho
skinparam nodesep 40
skinparam ranksep 60

class Partida {
  - jugadores : Jugadores
  - registro : RegistroPartida
  - fabricaFases: FabricaFases
  - anunciadorGanador: AnunciadorGanador
  - evaluadorGanador: EvaluadorGanador
  - sheriffRevelado: Jugador
  - faseActual : Fase

  + Partida(Jugadores, FabricaFases, AnunciadorGanador, EvaluadorGanador)
  + faseActual() : Fase
  + registrarVotoMafia(votante : Jugador, objetivo : Jugador)
  + elegirInvestigar(detective : Jugador, objetivo : Jugador)
  + elegirProteger(medico : Jugador, objetivo : Jugador)
  + revelarSheriff(sheriff : Jugador)
  + nominar(j : Jugador)
  + votar(votante : Jugador, objetivo : Jugador)
  + resolverFaseActual()
  + terminada() : boolean
  + resultado() : Optional<Bando>
  + anuncio() : Optional<String>
  + resumen() : String
  + jugadores() : Jugadores
}

abstract class Fase {
  # numeroRonda : int
  + {abstract} resolver() : RegistroRonda
  + {abstract} siguiente(partida : Partida) : Fase
  + {abstract} nombre() : String
  + numeroRonda() : int
  ~ registrarVotoMafia(votante : Jugador, objetivo : Jugador)
  ~ nominar(j : Jugador)
  ~ votar(votante : Jugador, objetivo : Jugador)
  ~ elegirInvestigar(detective : Jugador, objetivo : Jugador)
  ~ elegirProteger(medico : Jugador, objetivo : Jugador)
  ~ revelarSheriff(sheriff : Jugador)
}
together {
  class FaseNocturna {
    - jugadores : Jugadores
    - votacionMafia : VotacionMafia
    - resolucion : ResolucionNocturna
    ~ registrarVotoMafia(votante : Jugador, objetivo : Jugador)
    ~ elegirInvestigar(detective : Jugador, objetivo : Jugador)
    ~ elegirProteger(medico : Jugador, objetivo : Jugador)
    + resolver() : RegistroRonda
    + siguiente(partida : Partida) : Fase
    + nombre() : String
  }
  class FaseDiurna {
    - votacion : VotacionDiurna
    - revotacion : Optional<VotacionDiurna>
    ~ nominar(j : Jugador)
    ~ votar(votante : Jugador, objetivo : Jugador)
    ~ revelarSheriff(sheriff : Jugador)
    + resolver() : RegistroRonda
    + siguiente(partida : Partida) : Fase
    + nombre() : String
  }
}

class FabricaFases {
  - jugadores : Jugadores
  - criterioEmpate : CriterioEmpate
  - criterioConsenso : CriterioConsenso
  + FabricaFases(jugadores : Jugadores, criterioEmpate : CriterioEmpate, criterioConsenso : CriterioConsenso)
  + crearFaseNocturna(numeroRonda : int) : FaseNocturna
  + crearFaseDiurna(numeroRonda : int) : FaseDiurna
}

class VotacionMafia {
  - criterioConsenso : CriterioConsenso
  - votos : List<VotoMafia>
  + votar(votante : Jugador, objetivo : Jugador)
  + victimaElegida() : Optional<Jugador>
}
interface VotoMafia {
  + objetivo() : Jugador
  + esPrioritario() : boolean
}
together {
  class VotoNormal {
    + objetivo() : Jugador
    + esPrioritario() : boolean
  }
  class VotoPadrino {
    + objetivo() : Jugador
    + esPrioritario() : boolean
  }
}
interface CriterioConsenso {
  + evaluarConsenso(votos : List<VotoMafia>) : Optional<Jugador>
}
together {
  class Mayoria {
    + evaluarConsenso(votos : List<VotoMafia>) : Optional<Jugador>
  }
  class SinVictima {
    + evaluarConsenso(votos : List<VotoMafia>) : Optional<Jugador>
  }
}

class VotacionDiurna {
  - criterio : CriterioEmpate
  - nominados : Set<Jugador>
  - votos : Map<Jugador, Jugador>
  + nominar(j : Jugador)
  + votar(votante : Jugador, objetivo : Jugador)
  + masVotados() : List<Jugador>
  + obtenerNominados() : List<Jugador>
  + resolver() : Optional<Jugador>
  + generarBallotage() : Optional<VotacionDiurna>
}
interface CriterioEmpate {
  + desempatar(empatados : List<Jugador>) : List<Jugador>
  + generarBallotage(empatados : List<Jugador>) : Optional<VotacionDiurna>
}
together {
  class SinEliminacion {
    + desempatar(empatados : List<Jugador>) : List<Jugador>
  }
  class Ballotage {
    + desempatar(empatados : List<Jugador>) : List<Jugador>
    + generarBallotage(empatados : List<Jugador>) : Optional<VotacionDiurna>
  }
}

class ResolucionNocturna {
  - atacado : Jugador
  - protegidos : List<Jugador>
  + registrarAtaque(objetivo : Jugador)
  + registrarProteccion(objetivo : Jugador)
  + resolver() : Optional<Jugador>
}

class RegistroPartida {
  - registros : List<RegistroRonda>
  + agregarRegistro(r : RegistroRonda)
  + generarResumen() : String
}
abstract class RegistroRonda {
  # numeroRonda : int
  + {abstract} describir() : String
}
together {
  class RegistroNocturno {
    - victima : Jugador
    + describir() : String
  }
  class RegistroNocheTranquila {
    + describir() : String
  }
  class RegistroDiurno {
    - eliminado : Jugador
    + describir() : String
  }
  class RegistroSinEliminacionDiurna {
    + describir() : String
  }
  class RegistroBallotage {
    - empatados : List<Jugador>
    + describir() : String
  }
}

class Jugadores {
  - jugadores : List<Jugador>
  + agregar(j : Jugador)
  + cantidadDeVivos() : int
  + cantidadVivosDelBando(bando : Bando) : int
  + porCadaVivo(accion : Consumer<Jugador>)
}
class Jugador {
  - nombre : String
  - rol : Rol
  - carta : Carta
  - estado : Estado
  + nombre() : String
  + estaVivo() : boolean
  + eliminar()
  + bando() : Bando
  + perteneceA(otroBando : Bando) : boolean
  + esMafioso() : boolean
  + resultadoAlSerInvestigado() : Bando
  + elegirInvestigar(objetivo : Jugador)
  + elegirProteger(objetivo : Jugador)
  + actuarEnNoche(resolucion : ResolucionNocturna)
  ~ ejecutarAccionNocturna(resolucion : ResolucionNocturna)
  + crearVotoMafia(objetivo : Jugador) : VotoMafia
  + revelarseComoSheriff()
  + estaRevelado() : boolean
  + cartaVistaPor(jugadorQuePregunta : Jugador) : Carta
  + descripcionDeCarta() : String
}

abstract class Estado {
  + {abstract} estaVivo() : boolean
  + {abstract} actuarEnNoche(jugador : Jugador, resolucion : ResolucionNocturna)
}
together {
  class Vivo {
    + estaVivo() : boolean
    + actuarEnNoche(jugador : Jugador, resolucion : ResolucionNocturna)
  }
  class Eliminado {
    + estaVivo() : boolean
    + actuarEnNoche(jugador : Jugador, resolucion : ResolucionNocturna)
  }
}

abstract class Rol {
  + {abstract} bando() : Bando
  + {abstract} nombre() : String
  + resultadoAlSerInvestigado() : Bando
  + actuarEnNoche(resolucion : ResolucionNocturna)
  + elegirInvestigar(objetivo : Jugador)
  + elegirProteger(objetivo : Jugador)
  + revelarseComoSheriff()
  + estaRevelado() : boolean
  + crearVotoMafia(objetivo : Jugador) : VotoMafia
}

class Carta {
  + revelar()
  + descripcion() : String
}

interface Bando {
  + nombre() : String
  + esMismoBando(otro : Bando) : boolean
  + esMismoBandoQueMafia(mafia : BandoMafia) : boolean
  + esMismoBandoQueCiudadano(ciudadano : BandoCiudadano) : boolean
  + ganoSegun(jugadores : Jugadores) : boolean
}
together {
  class BandoMafia {
    + nombre() : String
    + ganoSegun(jugadores : Jugadores) : boolean
  }
  class BandoCiudadano {
    + nombre() : String
    + ganoSegun(jugadores : Jugadores) : boolean
  }
}

class Configuracion {
  - mezclador : MezcladorDeRoles
  - tramos : List<Tramo>
  + armarRoles(cantidadJugadores : int) : List<Rol>
  - tramoPara(cantidadJugadores : int) : Tramo
  - construirTramos() : List<Tramo>
}
class Tramo {
  - minimo : int
  - maximo : int
  - cantidadMafiosos : int
  - especialesFijos : List<Supplier<Rol>>
  - especialesCandidatos : List<Supplier<Rol>>
  - cantidadEspecialesAElegir : int
  + contiene(cantidadJugadores : int) : boolean
  + armarRoles(cantidadJugadores : int, mezclador : MezcladorDeRoles) : List<Rol>
}
class CantidadDeJugadoresInvalidaException

class RepartidorRoles {
  + repartir(nombres : List<String>, roles : List<Rol>) : Jugadores
}
interface MezcladorDeRoles {
  + mezclar(roles : List<Rol>)
}
class MezcladorAleatorioRoles {
  + mezclar(roles : List<Rol>)
}

Partida *-- Jugadores
Partida *-- RegistroPartida
Partida o-- "2" Bando : bandos
Partida --> Fase : faseActual
Partida --> CriterioEmpate : criterioEmpate
Partida --> CriterioConsenso : criterioConsenso

FabricaFases --> Jugadores : jugadores
FabricaFases --> CriterioEmpate : criterioEmpate
FabricaFases --> CriterioConsenso : criterioConsenso
FabricaFases ..> FaseNocturna : "crea"
FabricaFases ..> FaseDiurna : "crea"

Fase <|-- FaseNocturna
Fase <|-- FaseDiurna
FaseNocturna *-- ResolucionNocturna
FaseNocturna *-- VotacionMafia
FaseNocturna --> Jugadores : jugadores
FaseDiurna *-- VotacionDiurna : votacion

VotacionMafia --> CriterioConsenso : criterioConsenso
VotacionMafia o-- "0..*" VotoMafia : votos
VotacionMafia ..> Jugador
VotoMafia <|.. VotoNormal
VotoMafia <|.. VotoPadrino
CriterioConsenso <|.. Mayoria
CriterioConsenso <|.. SinVictima
Mayoria ..> VotoMafia

VotacionDiurna --> CriterioEmpate : criterio
VotacionDiurna ..> Jugador
CriterioEmpate <|.. SinEliminacion
CriterioEmpate <|.. Ballotage
CriterioEmpate ..> VotacionDiurna
Ballotage ..> SinEliminacion

RegistroPartida *-- "0..*" RegistroRonda
RegistroRonda <|-- RegistroNocturno
RegistroRonda <|-- RegistroNocheTranquila
RegistroRonda <|-- RegistroDiurno
RegistroRonda <|-- RegistroSinEliminacionDiurna
RegistroRonda <|-- RegistroBallotage

ResolucionNocturna o-- "0..*" Jugador

Jugadores o-- "5..12" Jugador
Jugador *-- Estado : estado
Jugador *-- Rol : rol
Jugador *-- Carta : carta
Estado <|-- Vivo
Estado <|-- Eliminado

Rol ..> Bando
Rol ..> VotoMafia
Bando <|.. BandoMafia
Bando <|.. BandoCiudadano

Configuracion *-- "3" Tramo
Configuracion --> MezcladorDeRoles : mezclador
Configuracion ..> CantidadDeJugadoresInvalidaException
Tramo ..> Rol

RepartidorRoles --> MezcladorDeRoles : mezclador
RepartidorRoles ..> Jugadores
MezcladorDeRoles <|.. MezcladorAleatorioRoles

FaseNocturna -[hidden]down- RegistroRonda
RegistroRonda -[hidden]down- ResolucionNocturna
Fase -[hidden]right- RegistroPartida
@enduml
