@startuml ModeloMafiaNucleo
skinparam classAttributeIconSize 0
skinparam linetype ortho
skinparam nodesep 40
skinparam ranksep 60

class Partida {
  - jugadores : Jugadores
  - registro : RegistroPartida
  - fabricaFases: FabricaFases
  - anunciadorGanador: AnunciadorGanador
  - evaluadorGanador: EvaluadorGanador
  - sheriffRevelado: Jugador
  - faseActual : Fase

  + Partida(Jugadores, FabricaFases, EvaluadorGanador, AnunciadorGanador)
  + faseActual() : Fase
  + registrarVotoMafia(votante : Jugador, objetivo : Jugador)
  + elegirInvestigar(detective : Jugador, objetivo : Jugador)
  + elegirProteger(medico : Jugador, objetivo : Jugador)
  + revelarSheriff(sheriff : Jugador)
  + nominar(j : Jugador)
  + votar(votante : Jugador, objetivo : Jugador)
  + resolverFaseActual()
  + terminada() : boolean
  + resultado() : Optional<Bando>
  + anuncio() : Optional<String>
  + resumen() : String
  + jugadoresEnMesa() : List<DatosJugador>
  + jugadoresVivos() : List<Jugador>
  + investigadoresDisponibles() : List<Jugador>
  + protectoresDisponibles() : List<Jugador>
}

abstract class Fase {
  # numeroRonda : int
  + {abstract} resolver() : RegistroRonda
  + {abstract} siguiente(fabricaFases : FabricaFases) : Fase
  + ejecutar(accion : AccionDePartida, partida : Partida)
  # {abstract} accionesDisponibles() : AccionesDisponibles
  + {abstract} nombre() : String
  + clave() : String
  + descripcion() : String
  + nominados() : List<Jugador>
  + votosRegistrados() : Map<Jugador, Jugador>
  + conteoVotos() : Map<Jugador, Long>
}
together {
  class FaseNocturna {
    - jugadores : Jugadores
    - votacionMafia : VotacionMafia
    - resolucion : ResolucionNocturna
    + registrar(accion : AccionVotoMafia)
    + registrar(accion : AccionInvestigar)
    + registrar(accion : AccionProteger)
    + resolver() : RegistroRonda
    + siguiente(fabricaFases : FabricaFases) : Fase
    + nombre() : String
  }
  class FaseDiurna {
    - votacion : VotacionDiurna
    - revotacion : Optional<VotacionDiurna>
    + registrar(accion : AccionNominar)
    + registrar(accion : AccionVotar)
    + registrar(accion : AccionRevelarSheriff, partida : Partida)
    + resolver() : RegistroRonda
    + siguiente(fabricaFases : FabricaFases) : Fase
    + nombre() : String
  }
}

interface AccionDePartida {
  + ejecutarEn(acciones : AccionesDisponibles, partida : Partida)
}
interface AccionesDisponibles {
  + ejecutarAccionNocturna(accion : Consumer<AccionesNocturnas>, excepcion : Supplier<RuntimeException>)
  + ejecutarAccionDiurna(accion : Consumer<AccionesDiurnas>, excepcion : Supplier<RuntimeException>)
}
interface AccionesNocturnas
interface AccionesDiurnas
class AccionesDisponiblesNocturnas
class AccionesDisponiblesDiurnas
class AccionVotoMafia
class AccionInvestigar
class AccionProteger
class AccionNominar
class AccionVotar
class AccionRevelarSheriff

class FabricaFases {
  - jugadores : Jugadores
  - criterioEmpate : CriterioEmpate
  - criterioConsenso : CriterioConsenso
  + FabricaFases(jugadores : Jugadores, criterioEmpate : CriterioEmpate, criterioConsenso : CriterioConsenso)
  + crearFaseNocturna(numeroRonda : int) : FaseNocturna
  + crearFaseDiurna(numeroRonda : int) : FaseDiurna
}

class VotacionMafia {
  - criterioConsenso : CriterioConsenso
  - votos : List<VotoMafia>
  + votar(votante : Jugador, objetivo : Jugador)
  + victimaElegida() : Optional<Jugador>
}
interface VotoMafia {
  + objetivo() : Jugador
  + esPrioritario() : boolean
}
together {
  class VotoNormal {
    + objetivo() : Jugador
    + esPrioritario() : boolean
  }
  class VotoPadrino {
    + objetivo() : Jugador
    + esPrioritario() : boolean
  }
}
interface CriterioConsenso {
  + evaluarConsenso(votos : List<VotoMafia>) : Optional<Jugador>
}
together {
  class Mayoria {
    + evaluarConsenso(votos : List<VotoMafia>) : Optional<Jugador>
  }
  class SinVictima {
    + evaluarConsenso(votos : List<VotoMafia>) : Optional<Jugador>
  }
}

class VotacionDiurna {
  - criterio : CriterioEmpate
  - nominados : Set<Jugador>
  - votos : Map<Jugador, Jugador>
  + nominar(j : Jugador)
  + votar(votante : Jugador, objetivo : Jugador)
  + masVotados() : List<Jugador>
  + obtenerNominados() : List<Jugador>
  + resolver() : Optional<Jugador>
  + generarBallotage() : Optional<VotacionDiurna>
  + analizarResultado() : ResultadoVotacion
}
interface ResultadoVotacion {
  + generarRegistro(numeroRonda : int) : RegistroRonda
  + obtenerSiguienteRonda() : Optional<VotacionDiurna>
}
class ResultadoEliminacion
class ResultadoBallotage
class ResultadoSinEliminacion
interface CriterioEmpate {
  + desempatar(empatados : List<Jugador>) : List<Jugador>
  + generarBallotage(empatados : List<Jugador>) : Optional<VotacionDiurna>
}
together {
  class SinEliminacion {
    + desempatar(empatados : List<Jugador>) : List<Jugador>
  }
  class Ballotage {
    + desempatar(empatados : List<Jugador>) : List<Jugador>
    + generarBallotage(empatados : List<Jugador>) : Optional<VotacionDiurna>
  }
}

class ResolucionNocturna {
  - atacado : Jugador
  - protegidos : List<Jugador>
  + registrarAtaque(objetivo : Jugador)
  + registrarProteccion(objetivo : Jugador)
  + resolver() : Optional<Jugador>
}

class RegistroPartida {
  - registros : List<RegistroRonda>
  + agregarRegistro(r : RegistroRonda)
  + generarResumen() : String
}
abstract class RegistroRonda {
  # numeroRonda : int
  + {abstract} describir() : String
}
together {
  class RegistroNocturno {
    - victima : Jugador
    + describir() : String
  }
  class RegistroNocheTranquila {
    + describir() : String
  }
  class RegistroDiurno {
    - eliminado : Jugador
    + describir() : String
  }
  class RegistroSinEliminacionDiurna {
    + describir() : String
  }
  class RegistroBallotage {
    - empatados : List<Jugador>
    + describir() : String
  }
}

class Jugadores {
  - jugadores : List<Jugador>
  + agregar(j : Jugador)
  + cantidadDeVivos() : int
  + cantidadVivosDelBando(bando : Bando) : int
  + vivos() : List<Jugador>
  + mafiososVivos() : List<Jugador>
  + vivosNoMafiosos() : List<Jugador>
  + investigadoresVivos() : List<Jugador>
  + protectoresVivos() : List<Jugador>
  + revelablesVivos() : List<Jugador>
  + porCadaVivo(accion : Consumer<Jugador>)
  + todos() : List<Jugador>
}
class Jugador {
  - nombre : String
  - rol : Rol
  - carta : Carta
  - estado : Estado
  + nombre() : String
  + estaVivo() : boolean
  + eliminar()
  + bando() : Bando
  + perteneceA(otroBando : Bando) : boolean
  + esMafioso() : boolean
  + resultadoAlSerInvestigado() : Bando
  + descripcionAlSerInvestigado() : String
  + elegirInvestigar(objetivo : Jugador)
  + elegirProteger(objetivo : Jugador)
  + actuarEnNoche(resolucion : ResolucionNocturna)
  ~ ejecutarAccionNocturna(resolucion : ResolucionNocturna)
  + crearVotoMafia(objetivo : Jugador) : VotoMafia
  + revelarse()
  + revelarJugador() : Jugador
  + resultadoInvestigacion() : Bando
  + cartaVistaPor(jugadorQuePregunta : Jugador) : Carta
  + descripcionDeCarta() : String
}

abstract class Estado {
  + {abstract} estaVivo() : boolean
  + {abstract} actuarEnNoche(jugador : Jugador, resolucion : ResolucionNocturna)
  + {abstract} siEstaVivo(jugador : Jugador, accion : Consumer<Jugador>)
}
together {
  class Vivo {
    + estaVivo() : boolean
    + actuarEnNoche(jugador : Jugador, resolucion : ResolucionNocturna)
  }
  class Eliminado {
    + estaVivo() : boolean
    + actuarEnNoche(jugador : Jugador, resolucion : ResolucionNocturna)
  }
}

abstract class Rol {
  + {abstract} bando() : Bando
  + {abstract} nombre() : String
  + rutaImagen() : String
  + resultadoAlSerInvestigado() : Bando
  + descripcionAlSerInvestigado() : String
  + ejecutar(accion : AccionDeRol)
}
interface AccionDeRol
class DatosJugador <<record>>
class Partidas
class EvaluadorGanador
class AnunciadorGanador

class Carta {
  + revelar()
  + descripcion() : String
}

interface Bando {
  + nombre() : String
  + esMismoBando(otro : Bando) : boolean
  + esMismoBandoQueMafia(mafia : BandoMafia) : boolean
  + esMismoBandoQueCiudadano(ciudadano : BandoCiudadano) : boolean
  + ganoSegun(jugadores : Jugadores) : boolean
}
together {
  class BandoMafia {
    + nombre() : String
    + ganoSegun(jugadores : Jugadores) : boolean
  }
  class BandoCiudadano {
    + nombre() : String
    + ganoSegun(jugadores : Jugadores) : boolean
  }
}

class Configuracion {
  - mezclador : MezcladorDeRoles
  - tramos : List<Tramo>
  + armarRoles(cantidadJugadores : int) : List<Rol>
  - tramoPara(cantidadJugadores : int) : Tramo
  - construirTramos() : List<Tramo>
}
class Tramo {
  - minimo : int
  - maximo : int
  - cantidadMafiosos : int
  - especialesFijos : List<Supplier<Rol>>
  - especialesCandidatos : List<Supplier<Rol>>
  - cantidadEspecialesAElegir : int
  + contiene(cantidadJugadores : int) : boolean
  + armarRoles(cantidadJugadores : int, mezclador : MezcladorDeRoles) : List<Rol>
}
class CantidadDeJugadoresInvalidaException

class RepartidorRoles {
  + repartir(nombres : List<String>, roles : List<Rol>) : Jugadores
}
interface MezcladorDeRoles {
  + mezclar(roles : List<Rol>)
}
class MezcladorAleatorioRoles {
  + mezclar(roles : List<Rol>)
}

Partida *-- Jugadores
Partida *-- RegistroPartida
Partida --> Fase : faseActual
Partida --> FabricaFases : fabricaFases
Partida --> EvaluadorGanador : evaluadorGanador
Partida --> AnunciadorGanador : anunciadorGanador
Partida ..> AccionDePartida
Partida ..> DatosJugador
Partidas ..> Partida : crea

FabricaFases --> Jugadores : jugadores
FabricaFases --> CriterioEmpate : criterioEmpate
FabricaFases --> CriterioConsenso : criterioConsenso
FabricaFases ..> FaseNocturna : "crea"
FabricaFases ..> FaseDiurna : "crea"

Fase <|-- FaseNocturna
Fase <|-- FaseDiurna
Fase ..> AccionesDisponibles
Fase ..> AccionDePartida
FaseNocturna ..|> AccionesNocturnas
FaseDiurna ..|> AccionesDiurnas
FaseNocturna *-- ResolucionNocturna
FaseNocturna *-- VotacionMafia
FaseNocturna --> Jugadores : jugadores
FaseDiurna *-- VotacionDiurna : votacion
AccionesDisponibles <|.. AccionesDisponiblesNocturnas
AccionesDisponibles <|.. AccionesDisponiblesDiurnas
AccionesDisponiblesNocturnas --> AccionesNocturnas
AccionesDisponiblesDiurnas --> AccionesDiurnas
AccionDePartida <|.. AccionVotoMafia
AccionDePartida <|.. AccionInvestigar
AccionDePartida <|.. AccionProteger
AccionDePartida <|.. AccionNominar
AccionDePartida <|.. AccionVotar
AccionDePartida <|.. AccionRevelarSheriff
AccionesNocturnas ..> AccionVotoMafia
AccionesNocturnas ..> AccionInvestigar
AccionesNocturnas ..> AccionProteger
AccionesDiurnas ..> AccionNominar
AccionesDiurnas ..> AccionVotar
AccionesDiurnas ..> AccionRevelarSheriff

VotacionMafia --> CriterioConsenso : criterioConsenso
VotacionMafia o-- "0..*" VotoMafia : votos
VotacionMafia ..> Jugador
VotoMafia <|.. VotoNormal
VotoMafia <|.. VotoPadrino
CriterioConsenso <|.. Mayoria
CriterioConsenso <|.. SinVictima
Mayoria ..> VotoMafia

VotacionDiurna --> CriterioEmpate : criterio
VotacionDiurna ..> Jugador
VotacionDiurna ..> ResultadoVotacion
ResultadoVotacion <|.. ResultadoEliminacion
ResultadoVotacion <|.. ResultadoBallotage
ResultadoVotacion <|.. ResultadoSinEliminacion
ResultadoBallotage --> VotacionDiurna
CriterioEmpate <|.. SinEliminacion
CriterioEmpate <|.. Ballotage
CriterioEmpate ..> VotacionDiurna
Ballotage ..> SinEliminacion

RegistroPartida *-- "0..*" RegistroRonda
RegistroRonda <|-- RegistroNocturno
RegistroRonda <|-- RegistroNocheTranquila
RegistroRonda <|-- RegistroDiurno
RegistroRonda <|-- RegistroSinEliminacionDiurna
RegistroRonda <|-- RegistroBallotage

ResolucionNocturna o-- "0..*" Jugador

Jugadores o-- "5..12" Jugador
Jugador *-- Estado : estado
Jugador *-- Rol : rol
Jugador *-- Carta : carta
Estado <|-- Vivo
Estado <|-- Eliminado

Rol ..> Bando
Rol ..> VotoMafia
Bando <|.. BandoMafia
Bando <|.. BandoCiudadano

Configuracion *-- "3" Tramo
Configuracion --> MezcladorDeRoles : mezclador
Configuracion ..> CantidadDeJugadoresInvalidaException
Tramo ..> Rol

RepartidorRoles --> MezcladorDeRoles : mezclador
RepartidorRoles ..> Jugadores
MezcladorDeRoles <|.. MezcladorAleatorioRoles

FaseNocturna -[hidden]down- RegistroRonda
RegistroRonda -[hidden]down- ResolucionNocturna
Fase -[hidden]right- RegistroPartida
@enduml
