@startuml ModeloMafiaRoles
skinparam classAttributeIconSize 0
skinparam linetype ortho
skinparam nodesep 45
skinparam ranksep 65

abstract class Rol {
  + {abstract} bando() : Bando
  + {abstract} nombre() : String
  + resultadoAlSerInvestigado() : Bando
  + elegirInvestigar(objetivo : Jugador)
  + elegirProteger(objetivo : Jugador)
  + actuarEnNoche(resolucion : ResolucionNocturna)
}

together {
  class Mafioso {
    + bando() : Bando
    + nombre() : String
  }
  class Ciudadano {
    + bando() : Bando
    + nombre() : String
  }
  class Padrino {
    + resultadoAlSerInvestigado() : Bando
    + nombre() : String
  }
  class Detective {
    - objetivoAInvestigar : Jugador
    - ultimoInvestigado : Jugador
    - resultadoInvestigacion : Bando
    + bando() : Bando
    + nombre() : String
    + elegirInvestigar(objetivo : Jugador)
    + actuarEnNoche(resolucion : ResolucionNocturna)
    + resultadoInvestigacion() : Bando
  }
  class Medico {
    - objetivoAProteger : Jugador
    - ultimoProtegido : Jugador
    + bando() : Bando
    + nombre() : String
    + elegirProteger(objetivo : Jugador)
    + actuarEnNoche(resolucion : ResolucionNocturna)
  }
  class Sheriff {
    + bando() : Bando
    + nombre() : String
  }
}

class Carta {
  - rol : Rol
  - estado : EstadoCarta
  + revelar()
  + descripcion() : String
}
interface EstadoCarta {
  + describir(rol : Rol) : String
}
together {
  class Oculta
  class Revelada
}

interface Bando {
  + esMismoBando(otro : Bando) : boolean
  + esMismoBandoQueMafia(mafia : BandoMafia) : boolean
  + esMismoBandoQueCiudadano(ciudadano : BandoCiudadano) : boolean
  + ganoSegun(jugadores : Jugadores) : boolean
}
together {
  class BandoMafia
  class BandoCiudadano
}

class ResolucionNocturna
class Jugador

Rol <|-- Mafioso
Rol <|-- Ciudadano
Mafioso <|-- Padrino
Rol <|-- Detective
Rol <|-- Medico
Rol <|-- Sheriff

Carta o-- Rol
Carta --> EstadoCarta : estado
EstadoCarta <|.. Oculta
EstadoCarta <|.. Revelada

Bando <|.. BandoMafia
Bando <|.. BandoCiudadano

Rol ..> Bando
Rol ..> ResolucionNocturna
Rol ..> Jugador
Detective ..> Jugador
@enduml
